services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
