version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
